### ISSUE TITLE
Same Day ACH

### ISSUE THREAD

**Issue by wadearnold** [moov-io/ach#429]
I wanted to see a same-day ACH file creation example and documentation. I also want to ensure that our library supports same-day ACH.

The use case example and file format is identified in this update from NACHA 
 
[Same Day ACH: FAQ](https://web.nacha.org/system/files/resource/2017-08/Same-Day-ACH-FAQ-2016_0.pdf)

**Comment by bkmoovio** [comment]
MegaCheck has been depreacted, but there is a check error in file.go 


megacheck ./...
Megacheck has been deprecated. Please use staticcheck instead.
file.go:308:9: assigning the result of this type assertion to a variable (switch batch := batch.(type)) could eliminate the following type assertions:
	/home/travis/gopath/src/github.com/moov-io/ach/file.go:310:59 (S1034)
server/repository.go:34:34: should use make(map[string]*ach.File) instead (S1019)
The command "megacheck ./..." exited with 1.

**Comment by bkmoovio** [comment]
Draft Proposal:

For the megacheck (staticcheck) issue:  Check batch.Category == CategoryNOC instead of the type assertion.

For the actual issue.
Modify file.go to have a new function isSameDay()

Range through batches:

If BatchHeader.EffectiveEntryDate is equal to FileHeader.CreationDate:

If BatchHeader.StandardEntryClassCode is equal to "IAT" return error.

Check if EntryDetail.Amount > 25,000 return error

**Comment by adamdecaf** [comment]
The megacheck fixes LGTM. 

From my reading `isSameDay() bool` should be triggered off `SD` (SD0130) as a prefix on `CompanyDescriptiveDate` and not other means. We should reject IAT and based on Amount if `isSameDay()` is true.

**Comment by bkmoovio** [comment]
That’s fine on the date.   I just started looking through it.  It wasn’t a final proposal.

Actually it does look like it may be effective date.  I’ll review and follow up later or in the am.

How will Same Day ACH transactions be identified?
Same Day ACH transactions would be identified and processed by the ACH Operator using that day’s date in the Effective Entry Date field of the batch of Same Day ACH transactions and meeting the ACH Operator processing deadline. If the entry contained a stale or invalid date in the Effective Entry Date field, the Operator will process the entry in the next available window, which could be same day or next day

**Comment by bkmoovio** [comment]
Since it (Company Descriptive Date) is discretionary/optional, I think the check on Effective Entry Date is needed, with a subsequent check on Company Descriptive Date field.


ODFIs at their discretion may require their Originators to further show intent for same-day settlement
using an optional, yet standardized, same-day indicator in the Company Descriptive Date field. The
Company Descriptive Date field (5 record, field 8) is an optional field with 6 positions available (positions
64-69). Currently, the Rules provide that the “Originator establishes this field as the date it would like to
see displayed to the Receiver for descriptive purposes.” NACHA recommends that, as desired, the content of this field be formatted using the convention “SDHHMM”, where the “SD” in positions 64- 65 denotes the intent for same-day settlement, and the hours and minutes in positions 66-69 denote the desired settlement time using a 24-hour clock. When electing to use this convention, the ODFI would validate that the field contains either.

**Comment by adamdecaf** [comment]
~~Yea. It seems like that `SD` check is something we need for sure while other fields might not be as good of an indicator for same-day ACH.~~

EffectiveEntryDate is the field we need to match on, but support `SD` is probably good too.

**Comment by bkmoovio** [comment]
In digging deeper, I am not convinced we need a code change as we support BatchHeader.EffectiveEntryDate and Batchheader.CompanyDescriptiveDate.

If EntryDetail.Amount > 25,000 ---

How would the $25,000 limit be enforced?
The ACH Operators will edit for the $25,000 limit for Same Day ACH transactions, and will assign next
day settlement to any transactions above the limit.

IAT can't be next day due to OFAC. 

To be continued!
