### ISSUE TITLE
file: parse timestamps in JSON ach.File representation

### ISSUE THREAD

**Issue by bkmoovio** [moov-io/ach#623]
Add parsing for for date time properties when creating an ach file from JSON.

Add validation for batch SEC Code when creating an ach file from JSON

**Comment by bkmoovio** [comment]
The file validation will do what is needed but if the batches are bad coming in from JSON, why create the file?

	// Build resulting file
	if err := file.setBatchesFromJSON(bs); err != nil {
		return nil, err
	}

An option would be to validate the batches in setBatchesFromJSON and return errors from setBatchesFromJSON.

**Comment by adamdecaf** [comment]
Our Read call (`func (r *Reader) Read() (File, error)`) returns whatever partial file is created also. I wanted to keep in line with that behavior. 

Also I'm hoping the error provides enough to go off of so that the calling code can fix the `ach.File` and re-validate in some trivial cases. That's a bit of a hope though and might just complicate calling code.
